repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'set -e; for f in "$@"; do docker run --rm -v "$(pwd):/workdir" -i trufflesecurity/trufflehog:latest filesystem "/workdir/$f" --results=verified,unknown --fail; done' --
        language: system
        stages: ["commit", "push"]
