// <auto-generated />
using System;
using ADproject.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Pocketree.Api.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260203232822_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ADproject.Models.Entities.Badge", b =>
                {
                    b.Property<int>("BadgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BadgeID"));

                    b.Property<string>("BadgeImageURL")
                        .HasColumnType("longtext");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CriteriaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<string>("RequiredDifficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("BadgeID");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("ADproject.Models.Entities.CommunityForest", b =>
                {
                    b.Property<int>("ForestTreeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ForestTreeID"));

                    b.Property<int>("MissionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("double");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("double");

                    b.HasKey("ForestTreeID");

                    b.HasIndex("MissionID");

                    b.ToTable("CommunityForests");
                });

            modelBuilder.Entity("ADproject.Models.Entities.GlobalMission", b =>
                {
                    b.Property<int>("MissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MissionID"));

                    b.Property<int>("CurrentTreeCount")
                        .HasColumnType("int");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PlantingFrequency")
                        .HasColumnType("int");

                    b.Property<int>("TotalRequiredTrees")
                        .HasColumnType("int");

                    b.HasKey("MissionID");

                    b.ToTable("GlobalMissions");

                    b.HasData(
                        new
                        {
                            MissionID = 1,
                            CurrentTreeCount = 0,
                            MissionName = "Greenify Sahara",
                            PlantingFrequency = 1,
                            TotalRequiredTrees = 1000
                        });
                });

            modelBuilder.Entity("ADproject.Models.Entities.Level", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LevelID"));

                    b.Property<string>("LevelImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MinCoins")
                        .HasColumnType("int");

                    b.HasKey("LevelID");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("ADproject.Models.Entities.Skin", b =>
                {
                    b.Property<int>("SkinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SkinID"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SkinPrice")
                        .HasColumnType("int");

                    b.HasKey("SkinID");

                    b.ToTable("Skins");
                });

            modelBuilder.Entity("ADproject.Models.Entities.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("CoinReward")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("RequiresEvidence")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TaskID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ADproject.Models.Entities.Tree", b =>
                {
                    b.Property<int>("TreeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TreeID"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWithered")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MissionID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TreeID");

                    b.HasIndex("MissionID");

                    b.HasIndex("UserID");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("ADproject.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("CurrentLevelID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FailedVerificationCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NotAttemptedTaskCount")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfileImageURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("ResetExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SupportQuery")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TotalCoins")
                        .HasColumnType("int");

                    b.Property<int>("UncompletedTaskCount")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("CurrentLevelID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserBadge", b =>
                {
                    b.Property<int>("UserBadgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserBadgeID"));

                    b.Property<int>("BadgeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEarned")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserBadgeID");

                    b.HasIndex("BadgeID");

                    b.HasIndex("UserID");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserPreference", b =>
                {
                    b.Property<int>("PreferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PreferenceID"));

                    b.Property<string>("PreferredCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PreferredDifficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PreferenceID");

                    b.HasIndex("UserID");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserSettings", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("EmailNotification")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("UseMlRecommendation")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserID");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserSkin", b =>
                {
                    b.Property<int>("UserSkinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserSkinID"));

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SkinID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserSkinID");

                    b.HasIndex("SkinID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSkins");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserTaskHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("UserTaskHistory");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserVoucher", b =>
                {
                    b.Property<int>("UserVoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserVoucherID"));

                    b.Property<bool>("IsRedeemed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RedemptionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VoucherID")
                        .HasColumnType("int");

                    b.HasKey("UserVoucherID");

                    b.HasIndex("UserID");

                    b.HasIndex("VoucherID");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("ADproject.Models.Entities.Voucher", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VoucherID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MinRedemptionLevel")
                        .HasColumnType("int");

                    b.Property<string>("VoucherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("VoucherID");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Pocketree.Api.Models.Entities.NotificationMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageID");

                    b.HasIndex("AdminID");

                    b.ToTable("NotificationMessages");
                });

            modelBuilder.Entity("ADproject.Models.Entities.CommunityForest", b =>
                {
                    b.HasOne("ADproject.Models.Entities.GlobalMission", "Mission")
                        .WithMany("PlantedTrees")
                        .HasForeignKey("MissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("ADproject.Models.Entities.Tree", b =>
                {
                    b.HasOne("ADproject.Models.Entities.GlobalMission", "GlobalMission")
                        .WithMany("Trees")
                        .HasForeignKey("MissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADproject.Models.Entities.User", "User")
                        .WithMany("Trees")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalMission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADproject.Models.Entities.User", b =>
                {
                    b.HasOne("ADproject.Models.Entities.Level", "CurrentLevel")
                        .WithMany()
                        .HasForeignKey("CurrentLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentLevel");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserBadge", b =>
                {
                    b.HasOne("ADproject.Models.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADproject.Models.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserPreference", b =>
                {
                    b.HasOne("ADproject.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserSettings", b =>
                {
                    b.HasOne("ADproject.Models.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("ADproject.Models.Entities.UserSettings", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserSkin", b =>
                {
                    b.HasOne("ADproject.Models.Entities.Skin", "Skin")
                        .WithMany()
                        .HasForeignKey("SkinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADproject.Models.Entities.User", null)
                        .WithMany("UserSkins")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserTaskHistory", b =>
                {
                    b.HasOne("ADproject.Models.Entities.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADproject.Models.Entities.User", "User")
                        .WithMany("TaskHistory")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ADproject.Models.Entities.UserVoucher", b =>
                {
                    b.HasOne("ADproject.Models.Entities.User", null)
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADproject.Models.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Pocketree.Api.Models.Entities.NotificationMessage", b =>
                {
                    b.HasOne("ADproject.Models.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ADproject.Models.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("ADproject.Models.Entities.GlobalMission", b =>
                {
                    b.Navigation("PlantedTrees");

                    b.Navigation("Trees");
                });

            modelBuilder.Entity("ADproject.Models.Entities.User", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("TaskHistory");

                    b.Navigation("Trees");

                    b.Navigation("UserBadges");

                    b.Navigation("UserSkins");

                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
