name: 2. Code Coverage

on:
  workflow_dispatch:
  schedule:
    - cron: "10 3 * * *"
  push:
    branches: ["main", "develop"]
    paths:
      - 'api/**'
      - '.github/workflows/2-code-coverage.yml'
permissions:
  contents: read
  actions: read

env:
  COVERAGE_MIN: "70"
jobs:
  api-code-coverage:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore api/api.sln

      - name: Run Tests with Coverage
        run: |
          dotnet test api/Pocketree.Api.Tests/Pocketree.Api.Tests.csproj \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults

      - name: Generate Coverage Report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:TestResults/**/coverage.cobertura.xml \
            -targetdir:coverage-report \
            "-reporttypes:Html;TextSummary"

      - name: Upload Coverage Artifacts
        if: always()
        uses: actions/upload-artifact@v6.0.0
        with:
          if-no-files-found: warn
          name: api-coverage-report
          path: |
            ${{ github.workspace }}/coverage-report/
            ${{ github.workspace }}/TestResults/**/coverage.cobertura.xml
